name: Build APK

on:
  push:
    branches:
      - uat  # Change this to your default branch if it's different
  pull_request:
    branches:
      - uat  # Change this to your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you want

      - name: Install dependencies
        run: |
          npm install
          npm install -g expo-cli

      - name: Build APK
        run: |
          expo build:android --no-publish --non-interactive --output ./packages/my-app.apk  # Adjust as needed
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: expo-apk
          path: ./packages/TotpAtWish-beta.apk  # Adjust the path to where the APK is generated
